apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: brukertest-portal
  namespace: teamsamtykkedigitalisering
  labels:
    team: teamsamtykkedigitalisering
spec:
  image: {{image}}
  port: 3000
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  # liveness:
  #   path: /status.html
  #   initialDelay: 5
  #   periodSeconds: 5
  #   failureThreshold: 30
  # readiness:
  #   path: /status.html
  #   initialDelay: 5
  #   periodSeconds: 5
  #   failureThreshold: 30
  # resources:
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 200m
  #     memory: 256Mi
  ingress:
    - https://brukertest-portal.dev.intern.nav.no
  