apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: brukertest-portal
  namespace: teamsamtykkedigitalisering
  labels:
    team: teamsamtykkedigitalisering
spec:
  image: {{image}}
  