apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: brukertest-portal
  namespace: teamsamtykkedigitalisering
  labels:
    team: teamsamtykkedigitalisering
spec:
  image: {{image}}
  port: 80
  team: teamsamtykkedigitalisering
  liveness:
    path: /isalive
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  
