apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: brukertest-portal
  namespace: teamsamtykkedigitalisering
  labels:
    team: teamsamtykkedigitalisering
spec:
  image: {{image}}
  port: 3000
  team: teamsamtykkedigitalisering
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  ingress:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  