FROM node:15.8.0

ENV HTTP_PORT=8080
ENV NODE_ENV=production

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

RUN yarn build

COPY dist dist/

RUN yarn install --production

CMD ["yarn", "prod"]