version: '3.9'
services:
    testdb:
        container_name: 'test_database'
        image: postgres
        networks:
            - brukertest_portal_backend
        env_file:
            - '.env.test'
        ports:
            - '${DB_PORT}:5432'
