version: '3.9'
services:
    app:
        container_name: brukertest_portal_backend
        build: 
            context: .
            dockerfile: Dockerfile
            target: source
        volumes: 
            - './src:/app/src'
        ports:
            - '${HTTP_PORT}:${HTTP_PORT}'
        env_file:
            - '.env'