FROM node:15.8.0

ENV HTTP_PORT=8080
ENV NODE_ENV=production

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn

RUN yarn build

RUN yarn install --production

EXPOSE 8080

CMD ["yarn", "prod"]