apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brukertest-portal-api
  namespace: teamsamtykkedigitalisering
  labels:
    team: teamsamtykkedigitalisering
spec:
  image: {{ image }}:{{ image_tag }}
  team: teamsamtykkedigitalisering
  port: 8080
  liveness:
    path: /isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /isready
    port: 8080
    initialDelay: 20
    timeout: 60
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingresses:
    - https://brukertest-portal-api.dev.intern.nav.no
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: "POSTGRES_12"
        databases:
          - name: "brukertest-portal-db"
            envVarPrefix: DB