apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brukertest-portal-api
  namespace: teamsamtykkedigitalisering
  labels:
    team: teamsamtykkedigitalisering
spec:
  image: {{ image }}
  team: teamsamtykkedigitalisering
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 5
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 5
  ingresses:
    - https://brukertest-portal-api.intern.nav.no
  azure:
    application:
      enabled: true
  gcp:
    sqlInstances:
      - type: "POSTGRES_12"
        databases:
          - name: "brukertest-portal-db"