name: Deploy backend to prod-gcp

on:
  push:
    branches: [main, feature/godkjenning-ved-endepunkter]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/brukertest-portal-backend:${{ github.sha }}
  IMAGE_LATEST: docker.pkg.github.com/${{ github.repository }}/brukertest-portal-backend:latest
  CLUSTER: prod-gcp
  RESOURCE: backend/.nais/nais_prod.yaml

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
          docker build . -t ${IMAGE} -t ${IMAGE_LATEST} -f Dockerfile.prod
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          docker push ${IMAGE_LATEST}
        working-directory: ./backend
  deploy:
    name: Deploy to prod-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Deploy to PROD
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: backend/.nais/nais_prod.yaml
          VAR: image=${{ env.IMAGE_LATEST }}
