name: Deploy frontend to prod-gcp

on:
  push:
    branches: [main, organiser-prosjekt-repo]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/brukertest-portal-frontend:${{ github.sha }}
  IMAGE_LATEST: docker.pkg.github.com/${{ github.repository }}/brukertest-portal-frontend:latest

jobs:
  build:
    name: Build and Push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
          yarn test
          docker build . -t ${IMAGE} -t ${IMAGE_LATEST}
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          docker push ${IMAGE_LATEST}
        working-directory: ./frontend
  deploy:
    name: Deploy to prod-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Deploy to PROD
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: frontend/.nais/nais_prod.yaml