
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
     # branches: [ main, organiser-prosjekt-repo ]
  pull_request:
     # branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
      - name: Install
        run: yarn install
        working-directory: ./frontend
      - name: Build
        run: yarn run build # will run `yarn build` command
        working-directory: ./frontend
      - name: Test
        run: yarn test # will run `yarn test` command
        working-directory: ./frontend
