name: "Build and deploy brukertest-portal"
on:
  push:
    branches:
    - "main"
    - "organiser-prosjekt-repo"
env:
  "IMAGE": "docker.pkg.github.com/${{ github.repository }}/brukertest-portal:${{ github.sha\
    \ }}"
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - run: ./build-frontend.sh
    # - name: "install dependencies"
    #   run: "npm ci"
    # - name: "run tests"
    #   run: "npm test"
    - name: "Build and publish Docker image"
      run: "docker build --pull --tag ${IMAGE} . && echo $GITHUB_TOKEN | docker login\
        \ --username $GITHUB_REPOSITORY --password-stdin https://docker.pkg.github.com\
        \ && docker push ${IMAGE}"
      env:
        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
  "deployAppToDev":
    name: "Deploy to dev"
    needs: "build"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to DEV"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "dev-gcp"
        "RESOURCE": ".nais/nais.yaml"
        "VARS": ".nais/dev.yaml"
  "deployAppToProd":
    name: "Deploy to prod"
    needs: "deployAppToDev"
    runs-on: "ubuntu-18.04"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Deploy to PROD"
      uses: "nais/deploy/actions/deploy@v1"
      env:
        "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
        "CLUSTER": "prod-gcp"
        "RESOURCE": ".nais/nais.yaml"
        "VARS": ".nais/prod.yaml"